version: "3.8"

services:
  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 "
    volumes:
      - ./app/:/dima-tech/app/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env-docker

  db:
    image: postgres:13.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env-docker
    ports:
      - "5433:5432"
